name: Go

on:
  push:
    branches: [ master ]
    
jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download dependencies
      run: go get ./...

    - name: Tidy modules
      run: go mod tidy
    
    - name: Make all
      run: make all
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vm-application-manager-linux.zip
        path: bundle/linux/*.zip
  
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Download dependencies
      run: go get ./...

    - name: Tidy modules
      run: go mod tidy
      
    - name: Make all
      run: nmake -f makefile.win

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vm-application-manager-windows.zip
        path: bundle/windows/*.zip
